name: MariaDB client

description: Install MariaDB client tools

runs:
  using: 'composite'
  steps:
    - name: Purge MariaDB common
      shell: bash
      run: |
        sudo apt purge mysql-common
        sudo rm -rf /etc/mysql /var/lib/mysql

    - name: Install MariaDB Repo
      shell: bash
      run: |
        sudo apt-get install wget software-properties-common dirmngr ca-certificates apt-transport-https -y
        wget https://r.mariadb.com/downloads/mariadb_repo_setup
        
        echo "c4a0f3dade02c51a6a28ca3609a13d7a0f8910cccbb90935a2f218454d3a914a  mariadb_repo_setup" | sha256sum -c -
        chmod +x mariadb_repo_setup
        sudo ./mariadb_repo_setup 
        sudo apt update

    - name: Install MariaDB client tools
      shell: bash
      run: sudo apt install libmariadb3 libmariadb-dev mariadb-client -y
