name: Install MariaDB client tools

runs:
  shell: bash
  using: 'composite'
  steps:
    - name: Purge MariaDB common
      run: |
        sudo apt purge mysql-common
        sudo rm -rf /etc/mysql /var/lib/mysql

    - name: Install MariaDB Repo
      run: |
        sudo apt-get install wget software-properties-common dirmngr ca-certificates apt-transport-https -y
        wget https://r.mariadb.com/downloads/mariadb_repo_setup
        echo "3a562a8861fc6362229314772c33c289d9096bafb0865ba4ea108847b78768d2  mariadb_repo_setup" | sha256sum -c -
        chmod +x mariadb_repo_setup
        sudo ./mariadb_repo_setup --mariadb-server-version="mariadb-10.6"
        sudo apt update

    - name: Install MariaDB client tools
      run: sudo apt install libmariadb3 libmariadb-dev mariadb-client -y
